opt_in_rules:
  - empty_count
included:
  - ../PopNetworking/Classes

# Configurable rules
force_cast: error # implicitly
force_try: error
line_length:
  - warning: 150
  - error: 170
type_body_length:
  - warning: 300
  - error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length: 20
identifier_name:
  min_length: 2
  max_length: 20
reporter: "xcode"
