use_frameworks!

target 'PopNetworking_Example' do
  pod 'PopNetworking', :path => '../'

  target 'PopNetworking_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
