platform :ios, '10.0'
use_frameworks!

target 'PopNetworking_Example' do
  pod 'PopNetworking', :path => '../'

  target 'PopNetworking_Tests' do
    inherit! :search_paths
    pod 'Pluralize.swift', :git => 'git@github.com:ajeferson/Pluralize.swift.git', :branch => 'feature/swift-update'
  end
end
